version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=cacaoaccounting
      - POSTGRES_USER=cacaoaccounting
      - POSTGRES_PASSWORD=cacaoaccounting
  app:
    environment: 
      - CACAO_ACCOUNTING = True
      - SERVER_THREADS = 4
      - DOCKERISED = True
      - SQLALCHEMY_DATABASE_URI = postgres://cacaoaccounting:cacaoaccounting@db:5432/cacaoaccounting
    build: .
    command: /bin/sh /app/entrypoint.sh
    ports:
      - "8080:8080"
    depends_on:
      - db