site_name: Cacao Accounting
theme: 
    name: material
    favicon: media/favicon.png
    logo: media/cacao_accounting.png
    palette:
        accent: teal
    repo_url: https://github.com/cacao-accounting/cacao-accounting
    repo_name: cacao-accounting/cacao-accounting
    icon:
        repo: fontawesome/brands/git-alt
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.sections

nav:
    - Inicio: index.md
    - Guía de Instalación:
        - Instalación: despliegue.md
        - Configuración: configuracion.md
        - Base de Datos:
          - Configuración de Base de Datos: database.md