site_name: Cacao Accounting
theme:
  name: material
  custom_dir: docs/theme_override_home/
  language: en
  favicon: media/favicon.png
  logo: media/cacao_accounting.png
  palette:
    accent: teal
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.tabs.link

repo_url: https://github.com/cacao-accounting/cacao-accounting
repo_name: cacao-accounting/cacao-accounting

copyright: Copyright &copy; 2024 - 2025 William Moreno Reyes

nav:
  - Home: index.md
  - Setup:
      - Introduction: setup.md
      - Containers Based Setup:
        - OCI Image: container.md
      - Python Package Based Setup:
        - Install from Pypi: py_pypi.md
        - Install from Sources: py_sources.md
        - Setup a Database:
            - Setup MySQL: py_database_mysql.md
            - Setup PostgreSQL: py_database_psql.md
        - Setup Systemd: py_systemd.md
        - Setup a Web Server: py_server.md
        - Setup a optional https sertificate: py_https.md
        - Setup a optional Redis Server: py_redis.md
      - Configuration: set_up.md
      - Database:
          - Database Setup: database.md
  - Contributors:
      - Contributing: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Changelog: changelog.md
  - About:
      - About: about.md
      - FAQ: faq.md
      - Dependecies: dependencies.md
  - Api: api.md

plugins:
  - blog
  - open-in-new-tab
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: es
          name: Español
          build: true
  - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cacao-accounting/cacao-accounting
    - icon: fontawesome/brands/docker
      link: https://quay.io/repository/cacaoaccounting/cacaoaccounting
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cacao-accounting/

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
