site_name: Cacao Accounting
theme:
  name: material
  custom_dir: docs/theme_override_home/
  language: es
  favicon: media/favicon.png
  logo: media/cacao_accounting.png
  palette:
    accent: teal
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.tabs.link

repo_url: https://github.com/cacao-accounting/cacao-accounting
repo_name: cacao-accounting/cacao-accounting

copyright: Copyright &copy; 2020 - 2021 William Moreno Reyes

nav:
  - Home: index.md
  - Setup:
      - Introducción: setup.md
      - Contenedor: container.md
      - Paquete Python: pypi.md
      - Desde las Fuentes: sources.md
      - Configuración: set_up.md
      - Base de Datos:
          - Configuración de Base de Datos: database.md
  - Contributors:
      - Guía para Colaboradores: CONTRIBUTING.md
      - Codigo de Conducta: CODE_OF_CONDUCT.md
      - Changelog: changelog.md
  - About:
      - General Information: about.md
      - FAQ: faq.md

plugins:
  - blog

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cacao-accounting/cacao-accounting
    - icon: fontawesome/brands/docker
      link: https://quay.io/repository/cacaoaccounting/cacaoaccounting

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
