environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python39"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python39-x64"

branches:
  only:
    - main
    - development
    - appveyor

services:
  - mssql2017

build_script:

install:
  - %PYTHON%\\python.exe -m pip install --upgrade pip setuptools wheel
  - %PYTHON%\\python.exe -m pip install -r requirements.txt
  - %PYTHON%\\python.exe -m pip install -r development.txt

test_script:
  - %PYTHON%\\python.exe -m pytest tests\database.py
  - %PYTHON%\\python.exe -m pytest