name: Contenedores

on:
  push:
    branches: [ main, development]
  pull_request:
    branches: [ main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Crear Contedor
      run: |
        buildah bud -t cacao-image .
    - name: Ejecutar Contenedor
      run: |
        podman volume create cacao-database
        podman pull mysql
        podman run -p 3306:3306 --restart on-failure --volume cacao-database:/var/lib/mysql --name cacaodb -e MYSQL_ROOT_PASSWORD=cacaodb -e MYSQL_DATABASE=cacaodb -e MYSQL_USER=cacaodb -e MYSQL_PASSWORD=cacaodb -d mysql
        podman run -p 8080:8080 --name cacao -e CACAO_ACCOUNTING=True -e CACAO_KEY=nsjksldknsdlkdsljdn -e CACAO_DB=mysql+pymysql://cacaodb:cacaodb@127.0.0.1:3306/cacaodb -d localhost/cacao-image
        podman container ls
    - name: Probar Contenedor
      run: |
        sleep 5
        podman container ls
