name: Contenedores

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Crear Contedor
      run: |
        buildah bud -t cacao-image .
    - name: Ejecutar Contenedor
      run: |
        # Mysql
        podman pod create --name cacao-pod -p 8080:8080 
        podman volume create cacao-database
        podman run --pod cacao-pod --name cacaodb --volume cacao-database:/var/lib/mysql  -e MYSQL_ROOT_PASSWORD=cacaodb -e MYSQL_DATABASE=cacaodb -e MYSQL_USER=cacaodb -e MYSQL_PASSWORD=cacaodb -d mysql:8
        podman run --pod cacao-pod --name cacao-mysql -e CACAO_ACCOUNTING=True -e CACAO_KEY=nsjksldknsdlkdsljdn -e CACAO_DB=mysql+pymysql://cacaodb:cacaodb@localhost:3306/cacaodb -d localhost/cacao-image
        # Postgresql
        podman pod create --name cacao-pod2 -p 8081:8080
        podman volume create cacao-database-pg
        podman run --pod cacao-pod2 --name cacaodb-pg --volume cacao-database-pg:/var/lib/postgresql/data -e POSTGRES_DB=cacaodb -e POSTGRES_USER=cacaodb -e POSTGRES_PASSWORD=cacaodb -d postgres:13
        podman run --pod cacao-pod2 --name cacao-postgresl -e CACAO_ACCOUNTING=True -e CACAO_KEY=nsjksldknsdlkdsljdn -e CACAO_DB=postgresql+pg8000://cacaodb:cacaodb@localhost:5432/cacaodb -d localhost/cacao-image
        sleep 10
        podman container ls
    - name: Probar Contenedor
      run: |
        podman pod stop cacao-pod2 cacao-pod
        podman pod start cacao-pod2 cacao-pod
        sleep 5
        podman container ls
        echo "Probando acceso a contenedor cacao-mysql"
        curl localhost:8080
        echo "Probando acceso a contenedor cacao-postgresl"
        curl localhost:8081
