name: Contenedores

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Crear Contedor
      run: |
        sudo podman pull registry.access.redhat.com/ubi8/ubi-minimal
        sudo buildah bud -t cacao-image .
    - name: Ejecutar Contenedor
      run: |
        # Mysql
        sudo podman pod create --name cacao-mysql -p 8888:8080
        sudo podman volume create cacao-database-mysql
        sudo podman run --pod cacao-mysql --name cacaodb-mysql --volume cacao-database-mysql:/var/lib/mysql  -e MYSQL_ROOT_PASSWORD=cacaodb -e MYSQL_DATABASE=cacaodb -e MYSQL_USER=cacaodb -e MYSQL_PASSWORD=cacaodb -d mysql:8
        sudo podman run --pod cacao-mysql --init --name cacao-accounting-mysql -e CACAO_ACCOUNTING=True -e CACAO_KEY=nsjksldknsdlkdsljdn -e CACAO_DB=mysql+pymysql://cacaodb:cacaodb@localhost:3306/cacaodb -d localhost/cacao-image
        # Postgresql
        sudo podman pod create --name cacao-postgresl -p 9999:8080
        sudo podman volume create cacao-database-postgresql
        sudo podman run --pod cacao-postgresl --name cacaodb-pg --volume cacao-database-postgresql:/var/lib/postgresql/data -e POSTGRES_DB=cacaodb -e POSTGRES_USER=cacaodb -e POSTGRES_PASSWORD=cacaodb -d postgres:13
        sudo podman run --pod cacao-postgresl --init --name cacao-accounting-postgresl -e CACAO_ACCOUNTING=True -e CACAO_KEY=nsjksldknsdlkdsljdn -e CACAO_USER=cacao -e CACAO_PWD=cacao -e CACAO_DB=postgresql+pg8000://cacaodb:cacaodb@localhost:5432/cacaodb -d localhost/cacao-image
    - name: Probar Contenedor
      run: |
        sudo podman pod stop cacao-mysql cacao-postgresl
        sudo podman pod start cacao-mysql cacao-postgresl
        sleep 30
        sudo podman container ls
        echo ""
        echo ""
        echo "Probando acceso a contenedor cacao-mysql"
        curl http://127.0.0.1:8888/info
        echo ""
        echo ""
        echo "Probando acceso a contenedor cacao-postgresl"
        curl http://127.0.0.1:9999/info
