name: Databases
on:
  workflow_run:
    workflows: [Coverage]
    types:
      - completed
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  multiple_db_check:
    name: Test with multiple databases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install python package
        env:
          CACAO_PRINT_DATABASE_URI: "True"
          CACAO_TEST: "True"
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r development.txt
          python -m pip install -e .
          python -m pip install psycopg2-binary
          cacaoctl setupdb
      - name: Test with Postgresql
        env:
          CACAO_PRINT_DATABASE_URI: "True"
          CACAO_TEST: "True"
        run: |
          # Enable postgresql serive
          sudo systemctl start postgresql.service
          # Run test on postgresql with pg8000.
          sudo -u postgres psql -c "CREATE DATABASE cacao;"
          sudo -u postgres psql -c "CREATE USER cacao WITH PASSWORD 'cacao';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE cacao TO cacao;"
          CACAO_DB=postgresql+pg8000://cacao:cacao@localhost/cacao cacaoctl setupdb
          # Run test on postgresql with psycopg2:
          sudo -u postgres psql -c "CREATE DATABASE cacao2;"
          sudo -u postgres psql -c "CREATE USER cacao2 WITH PASSWORD 'cacao2';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE cacao2 TO cacao2;"
          CACAO_DB=postgresql+psycopg2://cacao2:cacao2@localhost/cacao2 cacaoctl setupdb
      - name: Test with MySQL
        env:
          CACAO_PRINT_DATABASE_URI: "True"
          CACAO_TEST: "True"
        run: |
          sudo systemctl start mysql.service
          mysql --user=root --password=root < tests/setup_mysql.sql
          CACAO_DB=mysql+pymysql://cacao:cacao@localhost/cacao cacaoctl setupdb
