name: Coverage

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r development.txt
      - name: Test with pytest
        run: |
          CACAO_TEST=True python -m pytest  -v -s --exitfirst --slow=True --cov=cacao_accounting
      - name: Coveralls
        uses: coverallsapp/github-action@v2
