# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    services:
      mysql:
        image: mysql
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: cacaodb
        ports:
            - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: cacao
          POSTGRES_PASSWORD: cacao
          POSTGRES_DB: cacao
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r development.txt
        pip install psycopg2
        python setup.py develop
    - name: Proyecto distribuible
      run: |
        python -m pep517.build .
        twine check dist/* 
    - name: Lint with flake8
      run: flake8 cacao_accounting
    - name: Test with pytest
      run: pytest --cov=cacao_accounting
    - name: SQLite Backend
      run: pytest tests/ghactions/sqlite.py
    - name: MySQL Backend
      run: pytest tests/ghactions/mysql.py
    - name: Postgresql Backend
      run: pytest tests/ghactions/postgresql.py
    - name: Codecov
      uses: codecov/codecov-action@v1.0.11
