name: Coverage

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r development.txt
      - name: Test with pytest
        run: |
          SECRET_KEY=ASD123kljaAddS CACAO_TEST=True LOGURU_LEVEL=FATAL python -m pytest  -v -s --slow=True --cov=cacao_accounting
      - name: Coveralls
        uses: coverallsapp/github-action@v2
