name: Coverage

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r development.txt
      - name: Test with pytest
        run: |
          CACAO_TEST=True LOGURU_LEVEL=WARNING python -m pytest  -v -s --exitfirst --slow=True --cov=cacao_accounting --cov-append tests/test_basicos.py
          CACAO_TEST=True LOGURU_LEVEL=WARNING python -m pytest  -v -s --exitfirst --slow=True --cov=cacao_accounting --cov-append tests/test_forms.py
          CACAO_TEST=True LOGURU_LEVEL=WARNING python -m pytest  -v -s --exitfirst --slow=True --cov=cacao_accounting --cov-append tests/test_vistas.py
          CACAO_TEST=True LOGURU_LEVEL=WARNING python -m pytest  -v -s --exitfirst --slow=True --cov=cacao_accounting --cov-append tests/test_webactions.py
      - name: Coveralls
        uses: coverallsapp/github-action@v2
